### ISSUE TITLE
Drop either secStore.jquery or secStore.js.jquery from your Bower repo

### ISSUE THREAD

**Issue by itbra** [jas-/secStore.js#8]
Both files are deployed when installing your plugin via Bower. The only difference between them is a typo on line 10: `AES-encryption` vs. `AES encryption`.

**Comment by jas-** [comment]
Thanks for finding this. I wasn't aware of the outdated jQuery objects in the bower distribution. I have since updated the necessary bower installer package which is now @ `v0.1.3`.

If you wish to continue using the jQuery version you can manually use the [jQuery branch](https://github.com/jas-/secStore.js/tree/jquery-version).
